# https://taskfile.dev

version: '3'

vars:
  MODE: '{{.MODE | default "dev"}}'

tasks:
  init:
    cmds:
      - cat /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 10 > .secret_db_password_dev
      - cat /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 10 > .secret_db_root_password_dev
      - >
        sed "s|PATH_TO_DB_PASSWORD_FILE|${PWD}/.secret_db_password_dev|" .env.template
        | sed "s|PATH_TO_DB_ROOT_PASSWORD_FILE|${PWD}/.secret_db_root_password_dev|"
        | sed "s|PATH_TO_PROJECTS_DIR|${PWD}/projects|" > .env
      - python3 config.py .env

  up:
    cmds:
      - > 
        docker compose --env-file .env
        -f sage_dev/compose.yaml 
        -f sage_dev/compose.{{.MODE}}.yaml 
        up -d

  down:
    cmds:
      - >
        docker compose  --env-file .env 
        -f sage_dev/compose.yaml 
        -f sage_dev/compose.{{.MODE}}.yaml 
        down

  clean:
    cmds:
      - >
        docker compose  --env-file .env 
        -f sage_dev/compose.yaml 
        -f sage_dev/compose.{{.MODE}}.yaml 
        down -v
      - sudo rm -f projects/usctdp-bedrock/.env
      - sudo rm -rf projects/usctdp-bedrock/vendor
      - sudo rm -rf projects/usctdp-bedrock/web/app/themes/usctdp-theme/vendor
      - sudo rm -rf projects/usctdp-bedrock/web/app/themes/usctdp-theme/node_modules
      - sudo rm -rf projects/usctdp-bedrock/web/app/plugins/usctdp-mgmt/vendor

  deploy:
    cmds:
      - >
        python3 sage_dev/sage.py build 
        --project usctdp-bedrock --theme usctdp-theme
      - >
        python3 sage_dev/bedrock.py deploy
        --name usctdp-bedrock --chmod

  test-data-init:
    cmds:
      - >
        docker compose --env-file .env 
        -f sage_dev/compose.yaml 
        -f sage_dev/compose.{{.MODE}}.yaml 
        exec 
        --user www-data 
        --workdir /www/srv/usctdp-bedrock/web/wp 
        web sh -c 
        "wp usctdp import_sessions /www/srv/usctdp-bedrock/test_data/test_session_data.json; 
        wp usctdp gen_people;
        wp usctdp gen_registrations 300"


  test-data-clean:
    cmds:
      - >
        docker compose --env-file .env 
        -f sage_dev/compose.yaml 
        -f sage_dev/compose.{{.MODE}}.yaml 
        exec 
        --user www-data 
        --workdir /www/srv/usctdp-bedrock/web/wp 
        web 
        wp usctdp clean all

  shell-web-root:
    cmds:
      - >
        docker compose --env-file .env 
        -f sage_dev/compose.yaml 
        -f sage_dev/compose.{{.MODE}}.yaml 
        exec web bash 

  shell-web:
    cmds:
      - >
        docker compose --env-file .env 
        -f sage_dev/compose.yaml 
        -f sage_dev/compose.{{.MODE}}.yaml 
        exec --user www-data web bash 

  tail-log:
    cmds:
      - >
        docker compose --env-file .env 
        -f sage_dev/compose.yaml 
        -f sage_dev/compose.{{.MODE}}.yaml 
        exec --user www-data web tail -f /www/srv/usctdp-bedrock/web/wp/wp-admin/debug.log
