# https://taskfile.dev

version: '3'

vars:
  MODE: '{{.MODE | default "dev"}}'
  DEV_GROUP_NAME: '{{.DEV_GROUP_NAME | default "devs"}}'
  DEV_GROUP_ID: '{{.DEV_GROUP_ID | default "2001"}}'

tasks:
  init_perms:
    cmds:
      - sudo groupadd -g {{.DEV_GROUP_ID}} {{.DEV_GROUP_NAME}}
      - sudo usermod -a -G {{.DEV_GROUP_NAME}} $USER
      - sudo chgrp -R {{.DEV_GROUP_NAME}} projects
      - sudo chmod g+rw projects

  clean_perms:
    cmds:
      - sudo groupdel {{.DEV_GROUP_NAME}}

  up:
    cmds:
      - > 
        docker compose --env-file .env
        -f sage_dev/compose.yaml 
        -f sage_dev/compose.{{.MODE}}.yaml 
        up -d

  down:
    cmds:
      - >
        docker compose  --env-file .env 
        -f sage_dev/compose.yaml 
        -f sage_dev/compose.{{.MODE}}.yaml 
        down

  deploy:
    cmds:
      - >
        python3 sage_dev/sage.py build 
        --project usctdp-bedrock --theme usctdp-theme
      - >
        python3 sage_dev/bedrock.py deploy
        --name usctdp-bedrock --chmod

  shell-web:
    cmds:
      - >
        docker compose --env-file .env 
        -f sage_dev/compose.yaml 
        -f sage_dev/compose.{{.MODE}}.yaml 
        exec web bash 
