# https://taskfile.dev

version: '3'

includes:
  common:
    taskfile: ./Taskfile.common.yml
    vars: { MODE: dev }

tasks:
  init:
    cmds:
      - cat /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 10 > .secret_db_password_{{.MODE}}
      - cat /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 10 > .secret_db_root_password_{{.MODE}}
      - cat /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 10 > .secret_admin_password_{{.MODE}}
      - python3 gen_config.py .env.{{.MODE}}.template {{.MODE}}
      - python3 init_dev_perms.py .env.{{.MODE}} {{.MODE}}

  up:
    cmds:
      - "{{.DOCKER_COMPOSE}} up -d"

  up-cert-init:
    cmds:
      - python3 gen_nginx_config.py .env.{{.MODE}}.template sage_dev/nginx/prod.conf.init sage_dev/nginx/prod.conf 
      - "{{.DOCKER_COMPOSE}} up -d proxy web db"

  down:
    cmds:
      - "{{.DOCKER_COMPOSE}} down"

  clean:
    cmds:
      - "{{.DOCKER_COMPOSE}} down -v"
      - sudo rm -f projects/usctdp-bedrock/.env
      - sudo rm -rf projects/usctdp-bedrock/vendor
      - sudo rm -rf {{.THEME_HOME}}/vendor
      - sudo rm -rf {{.THEME_HOME}}/node_modules
      - sudo rm -rf {{.PLUGIN_HOME}}/vendor
      - sudo rm -rf {{.PLUGIN_HOME}}/node_modules

  deploy:
    cmds:
      - >
        python3 sage_dev/sage.py
        --web_container {{.PROJECT_NAME}}-web-1
        build
        --project usctdp-bedrock --theme usctdp-theme
      - "{{.DOCKER_COMPOSE}} exec --workdir {{.PLUGIN_HOME}} web npm install"
      - "{{.DOCKER_COMPOSE}} exec --workdir {{.PLUGIN_HOME}} web npm run dev"
      - >
        python3 sage_dev/bedrock.py
        --web_container {{.PROJECT_NAME}}-web-1 deploy
        --name usctdp-bedrock
      - sudo chgrp -R usctdp_devs projects
      - sudo chmod -R g+rw projects
      - "{{.DOCKER_COMPOSE}} exec --user www-data --workdir {{.WP_HOME}} web bash /app/scripts/web/install_wordpress.sh"
      - "{{.WP_CLI}} plugin activate woocommerce"
      - "{{.WP_CLI}} plugin activate usctdp-mgmt"
      - "{{.WP_CLI}} plugin activate user-switching"
      - "{{.WP_CLI}} theme activate usctdp-theme"

  build-theme:
    cmds:
      - >
        python3 sage_dev/sage.py
        --web_container {{.PROJECT_NAME}}-web-1
        build
        --project usctdp-bedrock --theme usctdp-theme

  dev-perms:
    cmds:
      - sudo chgrp -R usctdp_devs projects
      - sudo chmod -R g+rw projects
