# https://taskfile.dev

version: '3'

env:
  MODE: "dev"

vars:
  PROJECT_NAME: "usctdp_{{.MODE}}"
  DOCKER_COMPOSE: "docker compose --env-file .env -p {{.PROJECT_NAME}} -f sage_dev/compose.{{.MODE}}.yaml" 
  WP_HOME: /www/srv/usctdp-bedrock/web/wp
  WP_LOG: /www/srv/usctdp-bedrock/web/app/debug.log
  THEME_HOME: /www/srv/usctdp-bedrock/web/app/themes/usctdp-theme
  PLUGIN_HOME: /www/srv/usctdp-bedrock/web/app/plugins/usctdp-mgmt

tasks:
  init:
    cmds:
      - cat /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 10 > .secret_db_password_dev
      - cat /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 10 > .secret_db_root_password_dev
      - >
        sed "s|PATH_TO_DB_PASSWORD_FILE|${PWD}/.secret_db_password_dev|" .env.template
        | sed "s|PATH_TO_DB_ROOT_PASSWORD_FILE|${PWD}/.secret_db_root_password_dev|"
        | sed "s|PATH_TO_PROJECTS_DIR|${PWD}/projects|" > .env
      - python3 config.py .env

  up:
    cmds:
      - "{{.DOCKER_COMPOSE}} up -d"

  down:
    cmds:
      - "{{.DOCKER_COMPOSE}} down"

  docker-logs:
    cmds:
      - "{{.DOCKER_COMPOSE}} logs"

  clean:
    cmds:
      - "{{.DOCKER_COMPOSE}} down -v"
      - sudo rm -f projects/usctdp-bedrock/.env
      - sudo rm -rf projects/usctdp-bedrock/vendor
      - sudo rm -rf {{.THEME_HOME}}/vendor
      - sudo rm -rf {{.THEME_HOME}}/node_modules
      - sudo rm -rf {{.PLUGIN_HOME}}/vendor
      - sudo rm -rf {{.PLUGIN_HOME}}/node_modules

  deploy:
    cmds:
      - >
        python3 sage_dev/sage.py --web_container {{.PROJECT_NAME}}-web-1 build
        --project usctdp-bedrock --theme usctdp-theme
      - "{{.DOCKER_COMPOSE}} exec --workdir {{.PLUGIN_HOME}} web npm install"
      - "{{.DOCKER_COMPOSE}} exec --workdir {{.PLUGIN_HOME}} web npm run dev"
      - >
        python3 sage_dev/bedrock.py --web_container {{.PROJECT_NAME}}-web-1 deploy 
        --name usctdp-bedrock 
      - sudo chgrp -R usctdp_devs projects
      - sudo chmod -R g+rw projects

  build-theme:
    cmds:
      - >
        python3 sage_dev/sage.py build 
        --project usctdp-bedrock --theme usctdp-theme

  dev-perms:
    cmds:
      - sudo chgrp -R usctdp_devs projects
      - sudo chmod -R g+rw projects

  shell:
    cmds:
      - >
        {{.DOCKER_COMPOSE}}
        exec -it
        --user {{.U | default "www-data"}}
        {{.S | default "web"}} bash

  wp:
    cmds:
      - "{{.DOCKER_COMPOSE}} exec --user www-data --workdir {{.WP_HOME}} web wp {{.CLI_ARGS}}"

  tail-wp-log:
    cmds:
      - "{{.DOCKER_COMPOSE}} exec --user www-data web tail -n 50 -f {{.WP_LOG}}"

  sql:
    cmds:
      - >
        {{.DOCKER_COMPOSE}}
        exec -it db sh -c 
        'mariadb -u root 
        -p"$(cat /run/secrets/db_root_password_dev)"'
