# https://taskfile.dev

version: '3'

vars:
  MODE: '{{.MODE | default "dev"}}'
  DEV_GROUP_NAME: '{{.DEV_GROUP_NAME | default "devs"}}'
  DEV_GROUP_ID: '{{.DEV_GROUP_ID | default "2001"}}'

tasks:
  init:
    cmds:
      - sudo groupadd -fg {{.DEV_GROUP_ID}} {{.DEV_GROUP_NAME}}
      - sudo usermod -a -G {{.DEV_GROUP_NAME}} $USER
      - sudo chgrp -R {{.DEV_GROUP_NAME}} projects
      - sudo chmod -R g+rw projects
      - cat /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 10 > .secret_db_password_dev
      - cat /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 10 > .secret_db_root_password_dev
      - >
        sed "s|PATH_TO_DB_PASSWORD_FILE|${PWD}/.secret_db_password_dev|" .env.example
        | sed "s|PATH_TO_DB_ROOT_PASSWORD_FILE|${PWD}/.secret_db_root_password_dev|"
        | sed "s|PATH_TO_PROJECTS_FILE|${PWD}/projects|" > .env

  up:
    cmds:
      - > 
        docker compose --env-file .env
        -f sage_dev/compose.yaml 
        -f sage_dev/compose.{{.MODE}}.yaml 
        up -d

  down:
    cmds:
      - >
        docker compose  --env-file .env 
        -f sage_dev/compose.yaml 
        -f sage_dev/compose.{{.MODE}}.yaml 
        down

  clean:
    cmds:
      - >
        docker compose  --env-file .env 
        -f sage_dev/compose.yaml 
        -f sage_dev/compose.{{.MODE}}.yaml 
        down -v
      - sudo groupdel {{.DEV_GROUP_NAME}}

  deploy:
    cmds:
      - >
        python3 sage_dev/sage.py build 
        --project usctdp-bedrock --theme usctdp-theme
      - >
        python3 sage_dev/bedrock.py deploy
        --name usctdp-bedrock --chmod

  shell-web:
    cmds:
      - >
        docker compose --env-file .env 
        -f sage_dev/compose.yaml 
        -f sage_dev/compose.{{.MODE}}.yaml 
        exec web bash 
